### ISSUE TITLE
intermittent segfault on featureview draw

### ISSUE THREAD

**Issue by c-wilson** [klusta-team/klustaviewa#50]
Program raises segfault 11 during the updateGL() call in FeatureView.set_data() (line 1325). This intermittently happens when using the wizard to select 2 clusters. I can't figure out what makes any given cluster pair cause the fault.

This is intermittent in many datasets, but reproducible in one dataset that I have. This occurs on MacOS 10.10.3 but not on Windows (at least with the same clusters in the dataset I am using).

When it doesn't fault, this cluster pair creates a weird pattern on the featureview.
![segfault](https://cloud.githubusercontent.com/assets/5377850/7262508/370a832e-e848-11e4-96f8-a0fd9c9b2105.jpg)

I am working to see if I can fix today.

**Comment by nippoo** [comment]
Closed by #51.
