### ISSUE TITLE
error: package directory 'qtools' does not exist

### ISSUE THREAD

**Issue by cxrodgers** [klusta-team/klustaviewa#52]
Hello, I am trying to install klustaviewa on Linux Mint. I tried cloning the current version of the github repository, and also downloading the stable 0.3.0 source tarball. I always get: "error: package directory 'qtools' does not exist"

This occurs whether I run "pip install --user ." or "python setup.py build" in the source directory.

I think the "qtools" you have in mind is probably this one, but could you verify this to be true? I don't see it listed as a requirement.
https://github.com/rossant/qtools

I've installed the current github version of it, but for some reason the setup.py in klustaviewa is having trouble finding it. But I know that it is there because python and ipython find it no problem.
In [1]: import qtools
In [2]: qtools.__file__
Out[2]: '/home/chris/.local/lib/python2.7/site-packages/qtools/__init__.pyc'

It did not help to add /home/chris/.local/lib/python2.7/site-packages to either my $PATH or my $PYTHONPATH. Typically pip has no trouble finding requirements there anyway, though.

Thanks for any tips!!

**Comment by nippoo** [comment]
Yes, that's the one.

If you're downloading from source, you should either install all the packages separately, but better to keep up-to-date, you should symlink:

```
https://github.com/rossant/qtools: qtools/qtools/ (note the subdir) into klustaviewa/qtools
https://github.com/rossant/galry: galry/galry (note the subdir) into klustaviewa/galry
https://github.com/klusta-team/spikedetekt2: spikedetekt2 (note the subdir) into klustaviewa/spikedetekt2
https://github.com/klusta-team/kwiklib: kwiklib/kwiklib (note the subdir) into klustaviewa/kwiklib
```

Then you can ```python setup.py install``` or ```python setup.py develop``` depending whether you want to be able to update the version you're running by pulling the repository or not...

**Comment by cxrodgers** [comment]
Thanks! This fixed it.

I think you are missing a subdir on spikedetekt2 in your response. I had to make it spikedetekt2/spikedetekt2 to get it to work.

**Comment by nippoo** [comment]
Thanks for the heads-up!

**Comment by MarvinT** [comment]
Is there a reason you don't use submodules so that git clone --recursive will automatically pull all the required repositories and folders to the right spot?
