### ISSUE TITLE
Window position on start up

### ISSUE THREAD

**Issue by seacritasianman** [klusta-team/klustaviewa#68]
Whenever I start up klustaviewa via the windows command line, it opens up with the windows in this configuration: 

![badwindows](https://cloud.githubusercontent.com/assets/20893542/22217745/15bbc596-e159-11e6-8dff-a591c722a34e.PNG)

which is not the same as the default view, which I get by pressing "Reset views":

![goodwindows](https://cloud.githubusercontent.com/assets/20893542/22217766/20853c6e-e159-11e6-8f4e-529de1303047.PNG)

Is there a way to start the program with the default window view, or do you know why it's starting up in the not default window positions? Thanks.

**Comment by rossant** [comment]
Maybe try to delete `~/.klustaviewa` and try again (where `~` is your home folder, for example `C:\Users\yourname`)

**Comment by seacritasianman** [comment]
Worked like a charm, thanks!
